trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildProject
  steps:
  - script: |
      echo Starting .NET Core build
      dotnet restore
      dotnet build
    displayName: 'Build .NET Core Project'

